require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/multa", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Multum. As you add validations to Multum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Multum.create! valid_attributes
      get multa_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      multum = Multum.create! valid_attributes
      get multum_url(multum)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_multum_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      multum = Multum.create! valid_attributes
      get edit_multum_url(multum)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Multum" do
        expect {
          post multa_url, params: { multum: valid_attributes }
        }.to change(Multum, :count).by(1)
      end

      it "redirects to the created multum" do
        post multa_url, params: { multum: valid_attributes }
        expect(response).to redirect_to(multum_url(Multum.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Multum" do
        expect {
          post multa_url, params: { multum: invalid_attributes }
        }.to change(Multum, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post multa_url, params: { multum: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested multum" do
        multum = Multum.create! valid_attributes
        patch multum_url(multum), params: { multum: new_attributes }
        multum.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the multum" do
        multum = Multum.create! valid_attributes
        patch multum_url(multum), params: { multum: new_attributes }
        multum.reload
        expect(response).to redirect_to(multum_url(multum))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        multum = Multum.create! valid_attributes
        patch multum_url(multum), params: { multum: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested multum" do
      multum = Multum.create! valid_attributes
      expect {
        delete multum_url(multum)
      }.to change(Multum, :count).by(-1)
    end

    it "redirects to the multa list" do
      multum = Multum.create! valid_attributes
      delete multum_url(multum)
      expect(response).to redirect_to(multa_url)
    end
  end
end
